/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = [''];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL3R1cmFoYW5qYXMvRG9jdW1lbnQvVWRlbXkvQW5ndWxhci9Nb3NoIEhhbWVkYW5pL2RlcGxveS1kZW1vL3NyYy9hcHAvYWJvdXQvYWJvdXQuY29tcG9uZW50LmNzcy5zaGltLm5nc3R5bGUudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9Vc2Vycy90dXJhaGFuamFzL0RvY3VtZW50L1VkZW15L0FuZ3VsYXIvTW9zaCBIYW1lZGFuaS9kZXBsb3ktZGVtby9zcmMvYXBwL2Fib3V0L2Fib3V0LmNvbXBvbmVudC5jc3MiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7OyJ9
