/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './about.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from './about.component';
const styles_AboutComponent:any[] = [i0.styles];
export const RenderType_AboutComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_AboutComponent,data:{}});
export function View_AboutComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,0,(null as any),(null as any),1,'p',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i1.ɵted(-1,(null as any),['\n  about works!\n'])),(_l()(),i1.ɵted(-1,(null as any),
      ['\n']))],(null as any),(null as any));
}
export function View_AboutComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,0,(null as any),(null as any),1,'app-about',
      ([] as any[]),(null as any),(null as any),(null as any),View_AboutComponent_0,
      RenderType_AboutComponent)),i1.ɵdid(1,114688,(null as any),0,i2.AboutComponent,
      ([] as any[]),(null as any),(null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const AboutComponentNgFactory:i1.ComponentFactory<i2.AboutComponent> = i1.ɵccf('app-about',
    i2.AboutComponent,View_AboutComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL3R1cmFoYW5qYXMvRG9jdW1lbnQvVWRlbXkvQW5ndWxhci9Nb3NoIEhhbWVkYW5pL2RlcGxveS1kZW1vL3NyYy9hcHAvYWJvdXQvYWJvdXQuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL1VzZXJzL3R1cmFoYW5qYXMvRG9jdW1lbnQvVWRlbXkvQW5ndWxhci9Nb3NoIEhhbWVkYW5pL2RlcGxveS1kZW1vL3NyYy9hcHAvYWJvdXQvYWJvdXQuY29tcG9uZW50LnRzIiwibmc6Ly8vVXNlcnMvdHVyYWhhbmphcy9Eb2N1bWVudC9VZGVteS9Bbmd1bGFyL01vc2ggSGFtZWRhbmkvZGVwbG95LWRlbW8vc3JjL2FwcC9hYm91dC9hYm91dC5jb21wb25lbnQuaHRtbCIsIm5nOi8vL1VzZXJzL3R1cmFoYW5qYXMvRG9jdW1lbnQvVWRlbXkvQW5ndWxhci9Nb3NoIEhhbWVkYW5pL2RlcGxveS1kZW1vL3NyYy9hcHAvYWJvdXQvYWJvdXQuY29tcG9uZW50LnRzLkFib3V0Q29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPHA+XG4gIGFib3V0IHdvcmtzIVxuPC9wPlxuIiwiPGFwcC1hYm91dD48L2FwcC1hYm91dD4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7b0JDQUE7TUFBQSx3RUFBRzthQUFBLDJDQUVDO01BQUE7OztvQkNGSjtNQUFBOytCQUFBLFVBQUE7TUFBQTtJQUFBOzs7OyJ9
