/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = [''];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL3R1cmFoYW5qYXMvRG9jdW1lbnQvVWRlbXkvQW5ndWxhci9Nb3NoIEhhbWVkYW5pL2RlcGxveS1kZW1vL3NyYy9hcHAvbmF2YmFyL25hdmJhci5jb21wb25lbnQuY3NzLnNoaW0ubmdzdHlsZS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL1VzZXJzL3R1cmFoYW5qYXMvRG9jdW1lbnQvVWRlbXkvQW5ndWxhci9Nb3NoIEhhbWVkYW5pL2RlcGxveS1kZW1vL3NyYy9hcHAvbmF2YmFyL25hdmJhci5jb21wb25lbnQuY3NzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7OzsifQ==
