/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = [''];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL3R1cmFoYW5qYXMvRG9jdW1lbnQvVWRlbXkvQW5ndWxhci9Nb3NoIEhhbWVkYW5pL2RlcGxveS1kZW1vL3NyYy9hcHAvaG9tZS9ob21lLmNvbXBvbmVudC5jc3Muc2hpbS5uZ3N0eWxlLnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vVXNlcnMvdHVyYWhhbmphcy9Eb2N1bWVudC9VZGVteS9Bbmd1bGFyL01vc2ggSGFtZWRhbmkvZGVwbG95LWRlbW8vc3JjL2FwcC9ob21lL2hvbWUuY29tcG9uZW50LmNzcyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7In0=
